
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include "EventEmitters.h"
#include "Props.h"
#include "States.h"
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <react/renderer/textlayoutmanager/TextLayoutContext.h>
#include <jsi/jsi.h>
#include <react/renderer/components/androidtextinput/AndroidTextInputShadowNode.h>

namespace facebook::react {

JSI_EXPORT extern const char PasteTextInputComponentName[];

typedef AndroidTextInputShadowNode PasteTextInputShadowNode;

/*
 * `ShadowNode` for <PasteTextInput> component.
 */
//class PasteTextInputShadowNode final : public ConcreteViewShadowNode<
//    PasteTextInputComponentName,
//    PasteTextInputProps,
//    PasteTextInputEventEmitter,
//    PasteTextInputState,
//    true
//    > {
//public:
//    static ShadowNodeTraits BaseTraits() {
//        auto traits = ConcreteViewShadowNode::BaseTraits();
//        traits.set(ShadowNodeTraits::Trait::LeafYogaNode);
//        return traits;
//    }
//
//    using ConcreteViewShadowNode::ConcreteViewShadowNode;
//
//    PasteTextInputShadowNode(
//        ShadowNodeFragment const &fragment,
//        ComponentDescriptor const &componentDescriptor
//    );
//
//    void setContextContainer(
//        ContextContainer *contextContainer
//    );
//};

} // namespace facebook::react
