/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateStateH.js
 */
#pragma once

#include <react/renderer/components/androidtextinput/AndroidTextInputState.h>

namespace facebook::react {

typedef AndroidTextInputState PasteTextInputState;

//class PasteTextInputState {
//
//public:
//    int64_t mostRecentEventCount = 0;
//    int64_t cachedAttributedStringId{0};
//    AttributedString attributedString{};
//    AttributedString reactTreeAttributedString{};
//    ParagraphAttributes paragraphAttributes{};
//
//    PasteTextInputState(
//        int64_t mostRecentEventCount,
//        int64_t cachedAttributedStringId,
//        AttributedString attributedString,
//        AttributedString reactTreeAttributedString,
//        ParagraphAttributes paragraphAttributes
//    );
//
//    PasteTextInputState() = default;
//
//    PasteTextInputState(
//            const PasteTextInputState& previousState,
//            const folly::dynamic& data);
//
//    folly::dynamic getDynamic() const;
//    MapBuffer getMapBuffer() const;
//};

} // namespace facebook::react
