
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniCpp.js
 */

#include "PasteTextInputSpecs.h"

namespace facebook {
namespace react {

// NativeSvgRenderableModuleSpecJSI::NativeSvgRenderableModuleSpecJSI(const JavaTurboModule::InitParams &params)
//   : JavaTurboModule(params) {
//   methodMap_["isPointInFill"] = MethodMetadata {2, __hostFunction_NativeSvgRenderableModuleSpecJSI_isPointInFill};
//   methodMap_["isPointInStroke"] = MethodMetadata {2, __hostFunction_NativeSvgRenderableModuleSpecJSI_isPointInStroke};
//   methodMap_["getTotalLength"] = MethodMetadata {1, __hostFunction_NativeSvgRenderableModuleSpecJSI_getTotalLength};
//   methodMap_["getPointAtLength"] = MethodMetadata {2, __hostFunction_NativeSvgRenderableModuleSpecJSI_getPointAtLength};
//   methodMap_["getBBox"] = MethodMetadata {2, __hostFunction_NativeSvgRenderableModuleSpecJSI_getBBox};
//   methodMap_["getCTM"] = MethodMetadata {1, __hostFunction_NativeSvgRenderableModuleSpecJSI_getCTM};
//   methodMap_["getScreenCTM"] = MethodMetadata {1, __hostFunction_NativeSvgRenderableModuleSpecJSI_getScreenCTM};
//   methodMap_["getRawResource"] = MethodMetadata {1, __hostFunction_NativeSvgRenderableModuleSpecJSI_getRawResource};
// }


PasteTextInputSpecsJSI::PasteTextInputSpecsJSI(
    const JavaTurboModule::InitParams &params)
    : JavaTurboModule(params) {
//  methodMap_["install"] =
//      MethodMetadata{0, __hostFunction_NativeLiveMarkdownModuleSpecJSI_install};
}

std::shared_ptr<TurboModule> PasteTextInputSpecs_ModuleProvider(const std::string &moduleName, const JavaTurboModule::InitParams &params) {
//   if (moduleName == "PasteTextInputSpecs") {
//     return std::make_shared<PasteTextInputSpecsJSI>(params);
//   }
  return nullptr;
}

} // namespace react
} // namespace facebook
